services:
  # Postgres Database
  postgres:
    container_name: backend_postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: backend
      POSTGRES_PASSWORD: backend

  # Redis-Stack
  redis-stack:
    container_name: backend_redis_stack
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/data

  # NGINX
  nginx:
    image: nginx
    container_name: backend_nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro

volumes:
  postgres_data:
  redis_data:
